export const PERMISSIONS = {
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    MANAGE_USERS: 'MANAGE_USERS',
    VIEW_USERS: 'VIEW_USERS',
    MANAGE_ROLES: 'MANAGE_ROLES',
    VIEW_ROLES: 'VIEW_ROLES',
    MANAGE_ROOMS: 'MANAGE_ROOMS',
    MANAGE_INVENTORY: 'MANAGE_INVENTORY',
    MANAGE_CONTENT: 'MANAGE_CONTENT',
    MANAGE_SHIFTS: 'MANAGE_SHIFTS',
    VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
    MANAGE_BOOKINGS: 'MANAGE_BOOKINGS',
    MANAGE_INVOICES: 'MANAGE_INVOICES',
    MANAGE_SERVICES: 'MANAGE_SERVICES',
    VIEW_REPORTS: 'VIEW_REPORTS',
    MANAGE_VOUCHERS: 'MANAGE_VOUCHERS'
  };